version: '3'
services:
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    #user: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d

  chat_api:
    build:
      context: chat_api
      dockerfile: Dockerfile
    container_name: chat_api
    #command: bash -c 'while !</dev/tcp/docker.for.mac.localhost/5432; do sleep 1; done;'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://test:test@postgres/chat
      SERVICE_PORT: 5001
      LLAMA_HOST: 192.168.1.196      
      DATABASE_HOST: 192.168.1.196
      #SERVICE_HOST: 
    ports:
      - "5001:5001"
      - "2222:22"

  #exllama_api:
  #  build:
  #    context: exllama_api
  #    dockerfile: Dockerfile
  #  container_name: llama_api
  #  #command: bash -c 'while !</dev/tcp/docker.for.mac.localhost/5432; do sleep 1; done;'
  #  environment:
  #    MODEL_NAME: mistral-layla
  #  ports:
  #    - "7001:7001"
  #    - "8400:8000"
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            device_ids: ['0']
  #            capabilities: [gpu]

  tts_api:
    build:
      context: openvoice
      dockerfile: Dockerfile
    container_name: tts_api
    #command: bash -c 'while !</dev/tcp/docker.for.mac.localhost/5432; do sleep 1; done;'
    environment:
      MODEL_NAME: mistral-layla
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    ports:
      - "8001:5001"
      - "2224:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
